//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FibrexSupplierPortal.Mgment {
    
    
    public partial class AccessDenied {
        
        /// <summary>
        /// LeftSideMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FibrexSupplierPortal.Mgment.Control.LeftSideMenu LeftSideMenu;
        
        /// <summary>
        /// DashboardLeftSideMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FibrexSupplierPortal.Mgment.Control.DashboardLeftSideMenu DashboardLeftSideMenu;
    }
}
